[package]
name = "clipboard-sync"
version = "0.1.0"
edition = "2021"

[dependencies]
arboard = "3.3.0"
clap = { version = "4.4.11", features = ["derive", "env"] }
thiserror = "1.0.50"
tokio = { version = "1.35.0", features = [
    "fs",
    "macros",
    "net",
    "rt",
    "rt-multi-thread",
] }
tokio-tungstenite = { version = "0.21.0", features = ["native-tls"] }
tracing = "0.1.40"
tracing-subscriber = "0.3.18"
